apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: duytt10-capstone-cluster
  region: us-east-1

vpc:
  id: vpc-0efb22c8a9293a957
  subnets:
    private:
      us-east-1c:
        id: subnet-0c3e0550f1d9b91cb
      us-east-1d:
        id: subnet-0458624c0b65dd2b9
    public:
      us-east-1a:
        id: subnet-07244f2686d5f2fb9
      us-east-1b:
        id: subnet-07b74143bb3dafdef

managedNodeGroups:
  - name: P5-ng-1
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 20