apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: DuyTT10-capstone-cluster
  region: us-east-1

vpc:
  id: vpc-09e88610249f5dcef
  subnets:
    private:
      us-east-1a:
        id: subnet-0f7f9374a4f7bdc8c
      us-east-1b:
        id: subnet-0f7f9374a4f7bdc8c
    public:
      us-east-1a:
        id: subnet-0f7f9374a4f7bdc8c
      us-east-1b:
        id: subnet-0f7f9374a4f7bdc8c

nodeGroups:
  - name: P5-ng-1
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 20