apiVersion: apps/v1
kind: Deployment
metadata:
  name: duytt10-capstone-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
        - name: duytt10-capstone
          image: 041996649308.dkr.ecr.us-east-1.amazonaws.com/duytt10-clouddevopsengin-capstone:cc4d93e
          ports:
            - containerPort: 80
          env:
          - name: IMAGE_TAG
            valueFrom:
              configMapKeyRef:
                name: duytt10-capstone-config
                key: IMAGE_TAG